### ISSUE TITLE
Exit code improvements

### ISSUE THREAD

**Issue by RickardCardell** [logstash-plugins/logstash-input-exec#12]
Related stackoverflow post: http://stackoverflow.com/questions/35846907/logstash-error-handling-in-exec-input

The behaviour of the error handling in the exec-input is somewhat unintuitive: Specifying a file that doesn't exist throws an error in the log. But if the file exists and it exits with a non-zero exit code it is ignored.

I would expect that a command that returns a non-zero exit code is regarded as a failed command.

### Non existing script file -  expected behaviour
```
$ /opt/logstash/bin/logstash -e 'input { exec { command => "foobar"  interval=> 10 } } output { stdout {} }' -v

starting agent {:level=>:info}
starting pipeline {:id=>"main", :level=>:info}
Settings: Default pipeline workers: 2
Registering Exec Input {:type=>nil, :command=>"foobar", :interval=>10, :level=>:info}
Running exec {:command=>"foobar", :level=>:info}
Error while running command {:command=>"foobar", :e=>#<IOError: Cannot run program "foobar" (in directory "/asdf"): error=2, No such file or directory>, :backtrace=>["org/jruby/RubyIO.java:4380:in `popen'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-input-exec-2.0.6/lib/logstash/inputs/exec.rb:79:in `execute'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-input-exec-2.0.6/lib/logstash/inputs/exec.rb:43:in `inner_run'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-input-exec-2.0.6/lib/logstash/inputs/exec.rb:37:in `run'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.4.0-java/lib/logstash/pipeline.rb:342:in `inputworker'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.4.0-java/lib/logstash/pipeline.rb:336:in `start_input'"], :level=>:error}
Command completed {:command=>"foobar", :duration=>0.05, :level=>:info}
```
Easy to spot that input failed.

### Script exits with exit code 1 - silent and not so intuitive
```
$ cat myexit.sh
#!/bin/bash
exit 1
$ cmod +x myexit.sh

$ /opt/logstash/bin/logstash -e 'input { exec { command => "./myexit.sh"  interval=> 10 } } output { stdout {} }' -v

starting agent {:level=>:info}
starting pipeline {:id=>"main", :level=>:info}
Settings: Default pipeline workers: 2
Registering Exec Input {:type=>nil, :command=>"./myexit.sh", :interval=>10, :level=>:info}
Running exec {:command=>"./myexit.sh", :level=>:info}
Starting pipeline {:id=>"main", :pipeline_workers=>2, :batch_size=>125, :batch_delay=>5, :max_inflight=>250, :level=>:info}
Pipeline main started
Command completed {:command=>"./myexit.sh", :duration=>0.1, :level=>:info}
```
No sign of that the command exited with exit code 1.

**Comment by magnusbaeck** [comment]
Sounds very reasonable. How about storing the exit code in a `@metadata` subfield? Then you have the option to drop events resulting from a non-zero exit, but it's not done by default so we remain backwards compatible.

**Comment by RickardCardell** [comment]
Yes, good idea, I think that would be sufficient.
